name: Bug report
description: Report a reproducible defect
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include concrete reproduction details.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Flutter version, Go version, and any relevant config.
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I confirmed this is not a security vulnerability report (those go via SECURITY.md).
          required: true
        - label: I removed secrets from logs/screenshots.
          required: true
